-- MySQL Script generated by MySQL Workbench
-- 03/27/16 12:36:43
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_mco2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_mco2` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `db_mco2` ;

-- -----------------------------------------------------
-- Table `db_mco2`.`calamity_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_mco2`.`calamity_type` ;

CREATE TABLE IF NOT EXISTS `db_mco2`.`calamity_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `calamity_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mco2`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_mco2`.`location` ;

CREATE TABLE IF NOT EXISTS `db_mco2`.`location` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mun` INT NOT NULL,
  `zone` INT NOT NULL,
  `brgy` INT NOT NULL,
  `purok` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mco2`.`calamity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_mco2`.`calamity` ;

CREATE TABLE IF NOT EXISTS `db_mco2`.`calamity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `calamity_typeID` INT NOT NULL,
  `freq_year` DOUBLE NOT NULL,
  `locationID` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `calamity_idx` (`calamity_typeID` ASC),
  INDEX `location_idx` (`locationID` ASC),
  CONSTRAINT `typeca`
    FOREIGN KEY (`calamity_typeID`)
    REFERENCES `db_mco2`.`calamity_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `locationca`
    FOREIGN KEY (`locationID`)
    REFERENCES `db_mco2`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mco2`.`housetype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_mco2`.`housetype` ;

CREATE TABLE IF NOT EXISTS `db_mco2`.`housetype` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `housetype` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mco2`.`wall`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_mco2`.`wall` ;

CREATE TABLE IF NOT EXISTS `db_mco2`.`wall` (
  `id` INT NOT NULL,
  `wall_mat` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mco2`.`roof`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_mco2`.`roof` ;

CREATE TABLE IF NOT EXISTS `db_mco2`.`roof` (
  `id` INT NOT NULL,
  `roof_mat` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mco2`.`household`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_mco2`.`household` ;

CREATE TABLE IF NOT EXISTS `db_mco2`.`household` (
  `id` INT NOT NULL,
  `locationID` INT NOT NULL,
  `housetypeID` INT NOT NULL,
  `wallID` INT NOT NULL,
  `roofID` INT NOT NULL,
  INDEX `location_idx` (`locationID` ASC),
  INDEX `house_mat_idx` (`housetypeID` ASC),
  PRIMARY KEY (`id`),
  INDEX `wallhh_idx` (`wallID` ASC),
  INDEX `roofhh_idx` (`roofID` ASC),
  CONSTRAINT `locationhh`
    FOREIGN KEY (`locationID`)
    REFERENCES `db_mco2`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `house_mathh`
    FOREIGN KEY (`housetypeID`)
    REFERENCES `db_mco2`.`housetype` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `wallhh`
    FOREIGN KEY (`wallID`)
    REFERENCES `db_mco2`.`wall` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `roofhh`
    FOREIGN KEY (`roofID`)
    REFERENCES `db_mco2`.`roof` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mco2`.`crop_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_mco2`.`crop_type` ;

CREATE TABLE IF NOT EXISTS `db_mco2`.`crop_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `crop_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mco2`.`crop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_mco2`.`crop` ;

CREATE TABLE IF NOT EXISTS `db_mco2`.`crop` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `volume` INT NOT NULL,
  `line` BIGINT(20) NOT NULL,
  `crop_typeID` INT NOT NULL,
  `locationID` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `type_idx` (`crop_typeID` ASC),
  INDEX `locationc_idx` (`locationID` ASC),
  CONSTRAINT `typec`
    FOREIGN KEY (`crop_typeID`)
    REFERENCES `db_mco2`.`crop_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `locationc`
    FOREIGN KEY (`locationID`)
    REFERENCES `db_mco2`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mco2`.`aquani_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_mco2`.`aquani_type` ;

CREATE TABLE IF NOT EXISTS `db_mco2`.`aquani_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `aquani_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mco2`.`aquani`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_mco2`.`aquani` ;

CREATE TABLE IF NOT EXISTS `db_mco2`.`aquani` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `line` BIGINT(20) NOT NULL,
  `volume` INT NOT NULL,
  `aquani_typeID` INT NOT NULL,
  `locationID` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `type_idx` (`aquani_typeID` ASC),
  INDEX `locationq_idx` (`locationID` ASC),
  CONSTRAINT `typeaq`
    FOREIGN KEY (`aquani_typeID`)
    REFERENCES `db_mco2`.`aquani_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `locationq`
    FOREIGN KEY (`locationID`)
    REFERENCES `db_mco2`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
